language: python
python:
- 2.7
- 3.6

cache: pip

before_script:
- pip install pycodestyle
script:
- pycodestyle style tests setup.py
- python -m unittest discover
- VERSION=$(python -c "import style;print(style.__version__)")
- PYPI_VERSION=$(curl -s https://pypi.org/pypi/style/json | jq -r .info.version)

deploy:
  provider: pypi
  distributions: sdist bdist_wheel --universal
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    condition: $(printf "$VERSION\n$PYPI_VERSION" | sort -V | head -n 1) != $VERSION
    branch: master
    python: 3.6
